### ISSUE TITLE
How to install this correctly

### ISSUE THREAD

**Issue by onenessboy** [4n3ver/dynamo-calc#1]
Hi ,

I would like to use this program, but i am not aware of typscript. can you please let me know how to configure it . In instruction it just say npm install ? is that correct command please and also how can i setup aws profile as parameter please

**Comment by 4n3ver** [comment]
You can refer to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html to set up aws profile.

To build the binary you can run the following two commands:
```bash
$ npm install
$ npm run build-dist
```

The binary should be generated in `dist` folder.
